### PR TITLE
Add pool utilization stats endpoint

### PR DESCRIPTION
**Pull request by markan**
This has two purposes.

1) The first is to provide some insight into the pool usage when
   producing diagnostic error messages, and debugging overload
   behavior.

2) The second is to allow experimentation with heuristics for load
   shedding in chef-server. Being able to probe the queue depth enables
   more intelligent choices of when and where to fail.

### CODE REVIEW

**Comment by markan** [comment]
Well, looks like there's some fixes needed for R15. I'll take a look and fix in a bit.

**Comment by seth** [comment]
@markan is there something you'd like to come back to here given that you've updated support for recent Erlang versions?

**Comment by markan** [comment]
Rebased; looks like tests are failing intermittently on a few tests
in travis, but I can't repro locally.  I ran it in a loop for about 40 minutes (so about 240 total iterations) and had no failures. I know I've hit a few 'racy' tests, but I can't spot the issue here.

**Comment by seth** [comment]
Yeah, I recall now that there is something that happens in travis in an intermittent fashion that I never had the time to track down.

**Pull request merged**
