### PR TITLE
disable edown and lock_deps

### PR DESCRIPTION
**Pull request by juise**
On modern erlang versions (18), the build fail - https://github.com/seth/pooler/issues/55

### CODE REVIEW

**Comment by juise** [comment]
Up!

**Comment by seth** [comment]
Hey there.

I fixed the code to use the upstream remote for edown. This is building for me now on Erlang 18. Want to verify that master now builds for you?

**Comment by juise** [comment]
Awesome! It's work perfectly! You rock start )

Why do we need edow and rebar_lock_deps and concrete.mk? Maybe will be better to use rebar3? Do you mind it I try to migrate to rebar3!

**Comment by juise** [comment]
The issue https://github.com/seth/pooler/issues/55 can be closed anyway!

**Comment by seth** [comment]
The `concrete.mk` setup is a solution that helped smooth out some rough parts of earlier versions of rebar. Using edown is only a nice-to-have that provides doc generation into markdown that can then be viewed easily via github -- concrete makes the dependency one that only matters for dev and won't get pulled in if you are pulling in pooler as a dep of your project (should be the case). The lock deps stuff is I believe now handled natively in rebar3.

I'd be quite happy to look at a patch/PR for rebar3.

**Pull request closed without merging**
